<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>GakumasModManager</AssemblyName>
    <RootNamespace>GakumasModManager</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="MdXaml" Version="1.27.0" />
    <PackageReference Include="Notification.Wpf" Version="10.1.0" />
    <PackageReference Include="Stylet" Version="1.3.7" />
  </ItemGroup>

</Project>
